### ISSUE TITLE
How to use the pprof function ?

### ISSUE THREAD

**Issue by Wangzihao18** [openebs/jiva#247]
https://github.com/openebs/jiva/blob/06ae965ec74df6b92101024e32d36732c29bc22b/main.go#L64

I want to use the pprof and go-torch to generate the flamegraph of jiva. Where should I set the env PPROFILE to enable this function ?

**Comment by utkarshmani1997** [comment]
@Wangzihao18 you can set the env `PPROFILE=filename` in the deployment of controller and replicas.

**Comment by Wangzihao18** [comment]
@utkarshmani1997 .Is the deployment of controller and replicas in openebs-operator-1.2.0.yaml ?

**Comment by Wangzihao18** [comment]
Solved in https://openebs-community.slack.com/archives/C3NPGQ6G3/p1570677152052000
