### ISSUE TITLE
Dependency on uncommitted code

### ISSUE THREAD

**Issue by gouthamve** [openebs/jiva#26]
I haven't yet checked out the build script but trying to `go get` on linux made me have a WTF moment :P 

[This](https://github.com/openebs/jiva/blob/master/frontend/gotgt/frontend.go#L37) depends on `port.Stats` which exists only in this PR: https://github.com/openebs/gotgt/pull/9/files

Also, why is `openebs/gotgt` not vendored. /cc @kmova

**Comment by Gouthamve** [comment]
Adding @payes as you touched the relevant code.

**Comment by Gouthamve** [comment]
Okay, so I figured it out. A dependency manager called `trash` checks out the `stats` branch of `openebs/gotgt` and uses that.

Can we move to a simpler dependency manager? Or document this somewhere? Also the Makefile is incredibly complex and can be made simpler.

**Comment by kmova** [comment]
@Gouthamve  -- trash and drapper are used for building. This is inherited from the longhorn project. I agree, we should definitely simplify it. I updated the openebs/jiva/readme.md to mention that make uses dapper and trash.

**Comment by vishnuitta** [comment]
As per the above comment, readme is update. Hence, closing the issue.
