### ISSUE TITLE
Provide a mechanism to check the health of a controller and replica

### ISSUE THREAD

**Issue by kmova** [openebs/jiva#4]
It is possible that that container that is launching the controller/replica may be up and running, but either the communication to the replica's or from replica to underlying storage could be having issues. The client will detect such issues as IO errors. However, there needs to be a mechanism where maya should be able to check the health of VSM (controller or replica) and take necessary actions like restart, etc., 

This can be as simple as an script or docker exec command.

**Comment by payes** [comment]
Updated on the wiki page https://github.com/openebs/jiva/wiki/Curl-commands

**Comment by kmova** [comment]
This issue will be tracked via  https://github.com/openebs/openebs/issues/1977
